@startuml
title My first Diagram

participant RRM order 10
participant RRC order 20
participant LLIM order 30

participant CSC order 32
participant F1AP order 33
participant DF1AP order 35
participant NGU_F1U order 40
participant DUOAM order 50
participant DUMGR order 60

participant MAC order 70
participant RLC order 80


note over OAM: CM state change to "ACTIVE"

OAM -> RRM : RRM_OAM_CELL_CONFIG_REQ

RRM -> RRC : RRC_RRM_CELL_SETUP_REQ

RRC -> LLIM : CSC_LLIM_CONFIG_CELL_REQ

LLIM -> NGU_F1U : RRC_S1U_CELL_CONFIG_REQ
LLIM <- NGU_F1U : S1U_RRC_CELL_CONFIG_CNF

LLIM -> NGU_F1U : RRC_PDCP_CELL_CONFIG_REQ
LLIM <- NGU_F1U : PDCP_RRC_CELL_CONFIG_RESP

RRC <- LLIM : CSC_LLIM_CONFIG_CELL_RESP
RRM <- RRC :  RRC_RRM_CELL_SETUP_RESP

OAM <- RRM : RRM_OAM_CELL_CONFIG_RESP

note over DUOAM: CM state change to "DUOAM_DSM_ACTIVE"

DUOAM -> MAC : DUOAM_MAC_SCHEDULER_PARAMS_REQ

DUOAM <- MAC : MAC_DUOAM_SCHEDULER_PARAMS_RESP
DUOAM -> DUMGR : DUOAM_DUMGR_CELL_CONFIG_REQ

DUMGR -> MAC : DUMGR_MAC_CELL_CONFIG_REQ

DUMGR -> MAC : MAC_DUMGR_CELL_CONFIG_RESP

DUMGR -> RLC : DUMGR_RLC_CELL_CONFIG_REQ
DUMGR <- RLC : RLC_DUMGR_CELL_CONFIG_RESP

DUOAM <- DUMGR : DUMGR_DUOAM_CELL_CONFIG_RESP

DUMGR -> DF1AP : DCPM_DF1AP_F1_SETUP_REQ

DF1AP -> F1AP : f1Setup request

RRC -> RRM : RRC_RRM_F1_SETUP_REQ
RRC <- RRM : RRC_RRM_F1_SETUP_RESP

DF1AP <- F1AP : f1Setup response

RRM -> OAM : RRM_OAM_DU_CONFIG_IND



DUMGR <- DF1AP : DF1AP_DCPM_F1_SETUP_RESP

note over DUMGR: DU state change to "DU ACTIVE"
DUMGR -> DUOAM : DUMGR_DUOAM_F1_LINK_STATUS_IND

note over NGAP : NG SETUP

NGAP -> OAM  : NGAP_OAM_NGAP_LINK_STATUS_IND

OAM -> RRM : RRM_OAM_CELL_START_REQ

RRM -> RRC : RRC_RRM_CELL_START_REQ

CSC -> F1AP : F1AP_CSC_CU_CONFIG_UPDATE_REQ

F1AP -> DF1AP : gNBCUConfigurationUpdate




DF1AP -> DUMGR: DF1AP_DCPM_CU_CONFIG_UPDATE_REQ



DUMGR-> MAC : DUMGR_MAC_CELL_RECONFIG_REQ
DUMGR <- MAC : MAC_DUMGR_CELL_RECONFIG_RESP
DUMGR -> MAC : DUMGR_MAC_CELL_START_REQ
DUMGR <- MAC : DUMGR_MAC_CELL_START_RESP

DF1AP <- DUMGR : DCPM_DF1AP_CU_CONFIG_UPDATE_RESP


DUMGR -> DUOAM : DUMGR_DUOAM_CELL_STATUS_IND


DF1AP -> F1AP : gNBCUConfigurationUpdate ack
F1AP  -> CSC  :  F1AP_CSC_CU_CONFIG_UPDATE_RESP

RRC -> RRM :RRC_RRM_CELL_START_RESP

DUMGR -> DF1AP : DCPM_DF1AP_DU_CONFIG_UPDATE_REQ


DF1AP -> F1AP : gNBDUConfigurationUpdate
F1AP -> CSC : F1AP_CSC_DU_CONFIG_UPDATE_REQ
RRC -> RRM : RRC_RRM_DU_CONFIGURATION_UPDATE_REQ

RRM -> RRC : RRC_RRM_DU_CONFIGURATION_UPDATE_RESP


CSC -> F1AP : F1AP_CSC_DU_CONFIG_UPDATE_RESP
F1AP -> DF1AP : gNBDUConfigurationUpdate ack

DUMGR <- DF1AP : DF1AP_DCPM_DU_CONFIG_UPDATE_RESP

DUMGR <- MAC : MAC_DUMGR_UL_CCCH_MSG_IND

DUMGR -> MAC : DUMGR_MAC_CREATE_UE_ENTITY_REQ
DUMGR -> RLC : DUMGR_RLC_CREATE_UE_ENTITY_REQ


DUMGR <- RLC : RLC_DUMGR_CREATE_UE_ENTITY_RESP
DUMGR <- MAC : MAC_DUMGR_CREATE_UE_ENTITY_RESP

DUMGR -> DF1AP : DCPM_DF1AP_INITIAL_UL_RRC_MSG_TRANSFER

@enduml
